### ISSUE TITLE
Integrated Webpage deployment

### ISSUE THREAD

**Issue by dbdimitrov** [saezlab/ccc_protocols#10]
The webpage is now deployed at: https://ccc-protocols.readthedocs.io/en/latest/

To enable automatic deployment I need admin rights (i.e. we need to move the repo to an organisational account, no rush for this we can do it later).

PS. The logo is a piece of art as you will see - we can keep it or remove it.

**Comment by earmingol** [comment]
Lol, what a piece of art! haha
I can improve the image quality so it is not pixeled, and change the letter colors to improve the contrast with the website.

Also, thanks for deploying it! it looks great!

My minor comment is about the Tensor-c2c abbreviation (in the hoe and FAQs). Can you changed it for the full name instead? for some reason the "c2c" does not look good to me haha, I would prefer having "Tensor-cell2cell".

**Comment by dbdimitrov** [comment]
I will replace the abbreviation on next rebuild :)
