### ISSUE TITLE
Gini coeffs Python vs R

### ISSUE THREAD

**Issue by dbdimitrov** [saezlab/ccc_protocols#9]
In R I calculate gene coefficients separately, in Python Erick does it on the outer product

IMO, let's keep it as it is for now. Ultimately, the interpretation yields the same conclusions.

**Comment by earmingol** [comment]
If they are not in the quick starts I would modify the R version later to match the python implementation

**Comment by dbdimitrov** [comment]
Not in quickstarts, I agree to leave as they are for this iteration - I can adapt R code to be able to combine both source & target.

**Comment by dbdimitrov** [comment]
We agreed this is likely too minor.
